[package]
name = "ec"
version = "1.0.0"
authors = ["Tundra_Climate"]
description = "Create a commit using emojis"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
dirs = "5.0.1"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
